#!/usr/bin/env bash

set -e

GENERATED_SWIFT_SOURCE="/Users/nicklas/git/krouton/shared/build/generated/ksp/iosMain/resources/krouton"
GENERATED_SWIFT_DESTINATION="/Users/nicklas/git/krouton/KontinuitySample/KontinuitySample/Generated/Kontinuity"

echo "Generating Kontinuity Swift Package..."
echo ""
echo "  GENERATED_SWIFT_SOURCE=$GENERATED_SWIFT_SOURCE"
echo "  GENERATED_SWIFT_DESTINATION=$GENERATED_SWIFT_DESTINATION"
echo ""

echo "Cleaning destination..."
rm -rf "$GENERATED_SWIFT_DESTINATION"

echo "Creating destination..."
mkdir -p "$GENERATED_SWIFT_DESTINATION"

echo "Copying Swift files..."
cp -a "$GENERATED_SWIFT_SOURCE/." "$GENERATED_SWIFT_DESTINATION/"
