#!/usr/bin/env bash

set -e

KIT_FILENAME="KroutonKit.swift"

SRCROOT="/Users/nicklas/git/krouton/KontinuitySample"

INPUT_DIR="$SRCROOT/../shared/build/generated/ksp/iosMain/resources/krouton"
INPUT_KIT_FILE="$INPUT_DIR/$KIT_FILENAME"

OUTPUT_DIR="$SRCROOT/KontinuitySample/Generated/Kontinuity"
OUTPUT_FILE="$OUTPUT_DIR/KontinuityGen.swift"
OUTPUT_KIT_FILE="$OUTPUT_DIR/$KIT_FILENAME"

if [ -f "$OUTPUT_FILE" ]; then
  rm "$OUTPUT_FILE"
fi

# shellcheck disable=SC2129
find "$INPUT_DIR" -type f \(  -name "*.swift" -not -name "$KIT_FILENAME" \) -exec cat {} + >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "extension KotlinThrowable: Error {}" >> "$OUTPUT_FILE"

cat "$INPUT_KIT_FILE" > "$OUTPUT_KIT_FILE"
